Update wokwi_test.yaml

diff --git a/.github/workflows/wokwi_test.yaml b/.github/workflows/wokwi_test.yaml
--- a/.github/workflows/wokwi_test.yaml
+++ b/.github/workflows/wokwi_test.yaml
@@ -1,63 +1,66 @@
 name: wokwi_test
-on: [push, workflow_dispatch]
+# either manually started, or on a schedule
+on: [ push, workflow_dispatch ]
 jobs:
   wokwi_test:
+    # ubuntu
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repo
-        uses: actions/checkout@v3
-        with:
-          submodules: recursive
+    # need the repo checked out
+    - name: checkout repo
+      uses: actions/checkout@v3
+      with:
+        submodules: recursive
 
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.10'
-      - run: |
-          python --version
-          pip --version
-          pip install cocotb==1.8.1
-          cocotb-config --version
-
-      - name: Install OSS CAD tools
-        uses: YosysHQ/setup-oss-cad-suite@v2
-        with:
+    # install oss fpga tools
+    - name: install oss-cad-suite
+      uses: YosysHQ/setup-oss-cad-suite@v2
+      with:
           python-override: true
           github-token: ${{ secrets.GITHUB_TOKEN }}
+    - run: | 
+        yosys --version
+        iverilog -V
+        cocotb-config --libpython
+        cocotb-config --python-bin
 
-      - run: | 
-          yosys --version
-          iverilog -V
+    - name: checkout tt tools repo
+      uses: actions/checkout@v3
+      with:
+        repository: tinytapeout/tt-support-tools
+        path: tt
+        ref: tt07
 
-      - name: Checkout tt tools repo
-        uses: actions/checkout@v3
-        with:
-          repository: tinytapeout/tt-support-tools
-          path: tt
-          ref: tt07
+    # need python and requirements
+    - name: setup python
+      uses: actions/setup-python@v4
+      with:
+        python-version: '3.10'
+    - run: pip install -r tt/requirements.txt
 
-      - run: pip install -r tt/requirements.txt
+    # fetch the truth table
+    - name: fetch Verilog and build config
+      run: ./tt/tt_tool.py --create-user-config
 
-      - name: Fetch Verilog and build config
-        run: ./tt/tt_tool.py --create-user-config
+    # does the wokwi project have a truthtable?
+    - name: Check the truthtable exists
+      id: check_files
+      uses: andstor/file-existence-action@v2
+      with:
+        files: "src/truthtable.md"
 
-      - name: Check the truthtable exists
-        id: check_files
-        uses: andstor/file-existence-action@v2
-        with:
-          files: "src/truthtable.md"
+    - name: test
+      if: steps.check_files.outputs.files_exists == 'true'
+      run: |
+        cd src
+        make clean
+        make
+        # make will return success even if the test fails, so check for failure in the results.xml
+        ! grep failure results.xml
 
-      - name: Test
-        if: steps.check_files.outputs.files_exists == 'true'
-        run: |
-          cd src
-          make clean
-          make
-          ! grep failure results.xml
-
-      - name: Upload VCD
-        if: success() || failure()
-        uses: actions/upload-artifact@v3
-        with:
+    - name: upload vcd
+      if: success() || failure()
+      uses: actions/upload-artifact@v3
+      with:
           name: test-vcd
           path: src/*.vcd
